title = "dotfiles"
version = "0.0.1"

[ globals ]
author = "Shyam Padia"
DOTFILES_DIR = "$HOME/.dotfiles"
# package_manager = 'brew'

[ plugins ]

[ plugins.test ]
[ plugins.test.hello ]
src = "test/.testfile.yml"
dst = "$XDG_CONFIG_HOME/test/testfile2.yml"


[ plugins.nvim ]
deps = ["nvim"]
# scripts = ["git clone https://github.com/tmux-plugins/tpm.git ~/lalatest/tmp"]
[ plugins.nvim.custom ]
src = "./vim/custom/custom/"
dst = "$XDG_CONFIG_HOME/nvim/"
scripts = ["git clone https://github.com/tmux-plugins/tpm.git ~/lalatest/temp"]
[ plugins.nvim.lazyvim ]
src = "./vim/custom/lazyvim/"
dst = "$XDG_CONFIG_HOME/lazyvim/nvim/"


[ plugins.shell ]
[ plugins.shell.zsh ]
src = "oh-my-zsh/.zshrc"
dst = "$HOME/.zshrc"
deps = ["zsh", "sd", "adsfhk"]


[ plugins.plex ]
[ plugins.plex.tmux ]
src= "tmux/.tmux.conf"
dst= "$XDG_CONFIG_HOME/tmux/tmux.conf"
deps = ["tmux", "sesh"]
# scripts = ["git clone https://github.com/tmux-plugins/tpm.git $XDG_CONFIG_HOME/tmux/plugins/tpm"]


# [ terminals ]
# [ terminals.wezterm ]
# src= "wezterm/wezterm.lua"
# dst= "$XDG_CONFIG_HOME/wezterm/wezterm.lua"
# deps = ["wezterm"]
# [ terminals.kitty ]
# src= kitty/kitty.conf
# dst= "$XDG_CONFIG_HOME/kitty/kitty.conf"
# deps = ["kitty"]
# [ terminals.alacritty ]
# src= alacritty/alacritty.yml
# dst= "$XDG_CONFIG_HOME/alacritty/alacritty.yml"
# deps = ["alacritty"]


# [ filemanager ]
# [ filemanager.yazi ]
# src = yazi/yazi.toml
# dst = "$XDG_CONFIG_HOME/yazi/yazi.toml"
# deps = ["yazi"]
# [ filemanager.ranger ]
# src= ranger/rc.conf
# dst= "$XDG_CONFIG_HOME/ranger/rc.conf"
# deps = ["ranger"]


# [[ bat ]]
# src= "./bat/bat.conf"
# dst= "$XDG_CONFIG_HOME/bat/bat.conf"
# deps = ["bat"]


# [[ lazygit ]]
# src= "lazygit/config.yml"
# dst= "$XDG_CONFIG_HOME/lazygit/config.yml"
# deps = ["lazygit"]

# [ dependencies ]
# src= "./deps"
# [ dependencies.macos ]
# dst = "./deps"
# [ dependencies.linux ]
# dst = "./deps"

# [[ terminals.alacritty ]]
# src= alacritty/custom/alacritty.yml
# dst= "$XDG_CONFIG_HOME/alacritty/alacritty.yml"
# [[ terminals.kitty ]]
# src= kitty/custom/kitty.conf
# dst= "$XDG_CONFIG_HOME/kitty/kitty.conf"

# [[ starship ]]
# src= starship/custom/starship.toml
# dst= "$XDG_CONFIG_HOME/starship/starship.toml"
# [[ eza ]]
# src= exa/custom/.eza.toml
# dst= "$XDG_CONFIG_HOME/exa/eza.toml"
# [[ shell.bash ]]
# src= bash/custom/.bashrc
# dst= "$HOME/.bashrc"
# [[ shell.nushell ]]
# src= nushell/custom/config.toml
# dst= "$XDG_CONFIG_HOME/nu/config.toml"
# [[ git ]]
# src= git/custom/.gitconfig
# dst= "$HOME/.gitconfig"
# [[ plex.zellij ]]
# src= zellij/custom/zellij.yml
# dst= "$XDG_CONFIG_HOME/zellij/zellij.yml"
