#!/usr/bin/env bash
# author: @crizzy9
# This script installs various applications and symlinks configuration files

source ./helpers.sh
# set -e

# Install dotfiles and symlink config files to their appropriate location
install_dotfiles() {
    info 'installing dotfiles'
    local overwrite_all=false backup_all=false skip_all=false
    
    # Running install scripts in alphabetical order
    for installer in $(find . -name "install.sh" -not -path '*.symlink*' | sort); do
        program=$(basename $(dirname "${installer}"))
        user "Do you want to run ${installer}? [y]es, [n]o"
        read -n 1 action
        if [ $action == "y" ]; then
            chmod +x "${installer}"
            sh -c "${installer}"
            success "Finished installing ${program}"
        else
            skip "${program}"
        fi
    done
}

install_all() {
    # user "Do you want to setup git? [y]es, [n]o"
    # read -n 1 gc
    # if [ "$gc" == "y" ]; then
    #     setup_gitconfig
    # fi

    # checks if symlinks exist for zshrc -L to check if file exists -e to check if only symlink exists
    # TODO: Update to check via environment variables
    if [ ! -e "$HOME/.zshrc" ]; then
        user "Do you want to install Dotfiles? [y]es, [n]o"
        read -n 1 dotfiles
        if [ "$dotfiles" == "y" ]; then
            install_dotfiles
        fi
    else
        info "Dotfiles already installed"
        user "Do you want to reinstall Dotfiles? [y]es, [n]o"
        read -n 1 reinstall
        if [ "$reinstall" == "y" ]; then
            install_dotfiles
            success 'All installed!'
        else
            fail 'Dotfiles installation failed!'
        fi
    fi
}

# Install everything
# take additional user input as required here
user "Do you want to start the installation for dotfiles for zsh, nvim, brew? [y]es, [n]o"
read -n 1 start
if [ "$start" == "y" ]; then
    install_all
else
    fail 'Nothing installed!'
fi
